avogadro/mainwindow.cpp
Minimize the number of left dock panels
Change-Id: I728e2aad56ed14cd5f4cdcc5967ab172e6050807
=> Tabify the "Display Types" and "View" docks and hide file bar on Mac

avogadro/mainwindow.cpp
Bug showed most clearly at launch, with an empty panel.
Change-Id: Iea180749c094d143a4903cd328054217073afbe1
=> Make sure to populate the tool settings widget when switching tools.

avogadro/mainwindow.cpp
This prevents the application from crashing, and is generally going
to do what people expect - let them edit an empty molecule if they
remove all active molecules.
=> If the user deletes the last molecule, make a new one

avogadro/CMakeLists.txt
Use of the components argument enables us to only set Qt5_DIR rather than
the _DIR for each module.
=> Modernize the find Qt 5 calls

avogadro/mainwindow.cpp
Mac evidently does not send activate() signal after clicking.
Now clicking on a row will properly activate.
=> Fix activation for render/molecule tree view widgets

avogadro/mainwindow.cpp
Fixes minor bug with image export dialog
=> Switch macros Qt has redefined macros in Qt5 -> Q_OS_MAC.

CMakeLists.txt, cmake/CompilerFlags.cmake
Require C++11, require CMake 3.3, and make use of updated APIs.
=> Initial pass at modern CMake, bump minimum to 3.3

avogadro/backgroundfileformat.cpp, avogadro/mainwindow.cpp
This is a change in Qt 5 that causes issues with non-Latin characters in
file names, using the local 8 bit encoding should work as expected.
=> Use toLocal8Bit over toStdString for file names

avogadro/avogadro.cpp
This will be extended to support downloadable translations, but starts the process (e.g., finding and loading *.qm files for qt, qtbase, and avogadrolibs.
Need to set up PO/POT translations for avogadroapp too, but that's a separate issue
=> Add support for finding translations (qt_* qtbase_* and avogadrolibs*)

avogadro/CMakeLists.txt, avogadro/application.cpp, avogadro/application.h, avogadro/avogadro.cpp, avogadro/mainwindow.cpp, avogadro/mainwindow.h
On MacOS, double-click from the Finder is handled by Qt
using events. This ports the Application class from Avo1
to handle drag-to-icon or double-click events.
=> Support fileOpen events on Mac with a QApplication subclass

avogadro/icons/avogadro2.desktop
Hi,
This desktop configuration file is one of the best I've seen among cross-distro projects, but not all Linux desktop environments have a "Science" category (or submenu) in their application menu, the most notable example being Cinnamon, the default desktop environment of Linux Mint (which is one of the most popular Linux distros). They do often have an Education category, however, so I thought that maybe adding the "Education" category to the desktop configuration file might help users of these desktop environments find it. 
Thanks for your time and your great work in making high-quality chemistry software more available to the masses,
Brenton
=> Adding "Education" category

cmake/AvogadroCPack.cmake
Fixes #87.
Signed-off-by: Marcus D. Hanwell <marcus.hanwell@kitware.com>
=> Missing parentheses on endif statement in CMake

avogadro/mainwindow.cpp
It stores more information relevant to Avogadro than CML now, and should
have probably been the deafult for a while now.
=> Default to the Chemical JSON format

cmake/DeployQt5.cmake
This became necessary after Qt 5.9, making packages a little more
tedious to create. This should ensure packages have the appropriate
style available and don't look like 90s retro version fallbacks...
=> Add the logic to install the style plugins

avogadro/lastinstall/CMakeLists.txt
Fixes problems saving AVI (which uses JPG) on Mac at least
Version 1.1
Suite D4700 …
=> Make sure to install Qt image plugins on Mac and Windows

avogadro/mainwindow.cpp
Double loop to check the default behavior. If the first loop evaluates to false (on call, all plugins are false o ignore), load default behavior.
Signed-off-by: serk12 <marcprat_maso@hotmail.com>
Version 1.1
Suite D4700
of my …
=> Default behavior check

avogadro/mainwindow.cpp
In some cases Qt on Linux seems to allow files w/o extensions
Version 1.1
Suite D4700
license and I have …
=> Add .cjson extension if a filename has no extension on save.

cmake/AvogadroCPack.cmake, cmake/deploy-osx.cmake.in
Requires CMake 3.19 (available on build systems)
Version 1.1
Suite D4700
license and I have the right …
=> Add support for signing the app before generating DMG

cmake/Entitlements.plist, cmake/deploy-osx.cmake.in
Notarization failed because:
-all SO files were unsigned
-timestamps were needed
-executables needed hardened runtime
Version 1.1
Suite D4700
of my knowledge, is …
=> Sign all OB plugins for Mac notarization

avogadro/avogadro.cpp
Should prevent fully-transparent window bugs
Version 1.1
Suite D4700
license and I have the right under …
=> Drop alpha channel in the OpenGL context on Linux

avogadro/icons/avogadro2.desktop
error: file contains key "Categories[hu]" in group "Desktop Entry",
xsbut "Categories" is not defined as a locale string
Version 1.1
Suite D4700
of my knowledge, is …
=> Fix failing AppImage build

avogadro/mainwindow.cpp, avogadro/mainwindow.h
Fix #313
https://github.com/AppImage/AppImageKit/issues/124
Version 1.1
Suite D4700
license and I have …
=> On Linux / BSD platforms, use xdg-open - works with AppImage

avogadro/mainwindow.cpp
I was encountering an issue wherein saving a file without specifying an extension would write it as CJSON format, but add the `.cml` extension. This occurs since the 'Save As' code adds this extension by default, but does not set a writer, so the default one is used.
Additionally, users could expect a file with no explicit extension to be saved with a default extension that matches their currently selected filter, rather than always `.cml` or `.cjson`.
Both of these issues regarding default extensions are handled in this PR.
Signed-off-by: Aritz Erkiaga <aerkiaga3@gmail.com>
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
=> Improve 'Save As' extension choosing logic

avogadro/avogadro.cpp, avogadro/mainwindow.cpp
This fixes a very old issue I never got around to looking into where the dtors for plugins were not being called. Problem 1 is that the MainWindow was allocated on the heap and its destructor wasn't called. Problem 2 was that we had not parented the plugin instances. This appears to work as expected now, one plugin was deleting the molecule.
=> Parent the instances of plugins, stack mainwindow

avogadro/aboutdialog.cpp, avogadro/aboutdialog.ui
=> Remove non-translatable HTML from about dialog strings

cmake/AvogadroCPack.cmake
=> Make sure to fix all binaries in the Mac bundle

cmake/AvogadroCPackOptions.cmake.in, cmake/deploy-osx.cmake.in
=> Update some Mac DMG options to give a snapshot date

cmake/deploy-osx.cmake.in
=> Remove the extra fixup bundle for Mac

scripts/avogadro-remote.py
Refactored the complete code into connection class and added the check for socket connection
Version 1.1
Suite D4700
license and I have the right under that license …
=> Refactored code and added some exceptions avogadro-remote.py

cmake/AvogadroCPack.cmake
=> Make sure to grab openbabel*.dll on Windows package

avogadro/mainwindow.cpp, avogadro/mainwindow.h
Save the name of the tool, not the initial pointer That tool pointer doesn't receive the widget, molecule, etc. So we get the up-to-date one from the active glWidget
Version 1.1
Suite D4700
of my knowledge, is covered under …
=> Fix bug sending RPC script commands to tools

avogadro/mainwindow.cpp
Noticed while using this software that my active `cjson` file did not seem to appear in the title bar (Ubuntu 22.04, for reference). Tracked this down to the fact that `Variant` will not be instantiated correctly with a `String` `m_type` when a char array is passed and initialized via `setValue`, and the `AVO_UNUSED` path is called instead. To fix this, we can just set the `fileName` attribute as an `std::string` directly via `toStdString` rather than `toLocal8Bit().data()`. 
Before: 
After:
Version 1.1
Suite D4700
Developer's …
=> Ensure that title bar correctly displays active molecule file

avogadro/mainwindow.cpp
As File>Export has multiple options, what exactly the toolbar button exports is not very clear.
This actually confused me as a user myself once upon a time so figured it was a good thing to try and fix myself.
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to …
=> Reduce ambiguity of "Export" toolbar button

cmake/AvogadroCPack.cmake
=> Make sure to copy libopenbabel on Mac for CPack

avogadro/mainwindow.cpp
=> Keep the QCocoaMessageBox code for Qt5

avogadro/avogadro.cpp
Version 1.1
Suite D4700
work with …
=> Fix build with Qt6 (needs Qt::endl namespace)

CMakeLists.txt, SECURITY.md
Version 1.1
Suite D4700
work with …
=> Bump version for 1.99 release

avogadro/mainwindow.cpp
Reverts OpenChemistry/avogadroapp#504
At the moment, this requires corresponding changes in Molequeue.
Until then, revert so builds work.
=> Revert "Port QRegExp to QRegularExpression"

avogadro/mainwindow.cpp
Should generally improve speed
Version 1.1
Suite D4700
work with modifications, whether created in …
=> Change defaults to turn off shadows, depth blur, and edge

.github/workflows/build_cmake.yml, avogadro/CMakeLists.txt, avogadro/mainwindow.cpp
=> Qt6: restore QRegExp port, remove Qt6Core5Compat dependency

README.md
The previously indicated address to locally build Avogadro2 appears defunct. 
Version 1.1
Suite D4700 …
=> indicate the newer compilation guide

avogadro/mainwindow.cpp
=> Use QDesktopServices on Linux too with Qt 6, which fixes opening URLs

.github/workflows/flatpak.yml, flatpak/org.openchemistry.Avogadro2.yaml
=> Use Qt/KDE runtime 6.8 for Flatpak test builds

avogadro/avogadro.cpp
I'd like to see if this crashes things on Windows
Version 1.1
Suite D4700
work with modifications, …
=> Only set the default context on Mac

avogadro/backgroundfileformat.cpp
Fixes https://github.com/OpenChemistry/avogadrolibs/issues/1689
Version 1.1
Suite D4700
work with …
=> Read UTF-16 files through Qt decoding to a temporary file

flatpak/org.openchemistry.Avogadro2.yaml
=> Build OpenBabel as separate module like in actual Flatpak

avogadro/avogadro.cpp
Seems to work, but crashes until shaders are updated
Version 1.1
Suite D4700
work with modifications, …
=> Update OpenGL to request 4.0 core profile

avogadro/mainwindow.cpp
Previously, openFile() was called directly which would crash because the background thread would get killed before finishing
Version 1.1
Suite D4700
license and I …
=> When multiple files are dropped, make sure to queue them for reading

flatpak/org.openchemistry.Avogadro2.yaml
=> Update CI flatpak manifest to match the newer libmsym version being used
