- avogadro/mainwindow.cpp
Fixed #11
Change-Id: I7d08c60a3c98aa31c2831070a9e3bdf9df32ed58
> Make sure to activate draw (or navigate) tool at launch.

- avogadro/mainwindow.cpp
Fixes issue #14.
Change-Id: I6b1b228543442370b077f1322d7de4dd421d924d
> Make sure to un-highlight edit/view tools when switching.

- CMakeLists.txt
Change-Id: I14be371a5ce92d4cb7276200213f17c61415414c
> Bumped the version to 0.9.0

- avogadro/lastinstall/CMakeLists.txt
Use the unversioned directories to make packaging simpler.
> Removed the Open Babel version number from the plugins

- avogadro/mainwindow.cpp
Added undo and redo command descriptions to their respective
main window QActions.
> Added undo and redo command descriptions.

- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
Once avogadrolibs supports tool priorities, we'll sort tools too.
> Merge "edit" and "tool" toolbars into one.

- avogadro/CMakeLists.txt
- avogadro/avogadro.cpp
- avogadro/mac.mm
Also removes "Show Tab Bar" on 10.12 and later.
Thanks to agarny at forum.qt.io & OpenCOR project.
> Add some Objective C++ to remove emoji and dictation menu items.

- avogadro/mainwindow.cpp
Also fixes problems with selecting rows in the display & molecule
tables in the interface.
> Fix Mac toolbar weirdness - a white box would always appear

- avogadro/CMakeLists.txt
Change the modules we search for.
> Minor updates to work with update-vtk from avogadrolibs

- avogadro/mainwindow.cpp
Adds saveFileIfNeeded() check for importFile() and openRecentFile()
> Adds saveFileIfNeeded() check while opening new file

- avogadro/avogadro.cpp
Commenting out setSamples() command.
> Disabling multisampling

- avogadro/mainwindow.cpp
- avogadro/mainwindow.ui
- avogadro/rpclistener.cpp
Add an explicit close action, improve the save-before-close dialog (porting from Avo1), etc.
> More interface cleanups

- avogadro/mainwindow.cpp
Fix issue #82, revert to previous ordering for adding recent files.
Signed-off-by: Marcus D. Hanwell <marcus.hanwell@kitware.com>
> Fix the recent file menu

- cmake/AvogadroCPack.cmake
Fixes https://github.com/OpenChemistry/avogadrolibs/issues/308
Signed-off-by: Geoffrey Hutchison <geoff.hutchison@gmail.com>
> Set INSTALL_BUNDLE_FILES to ON for Mac builds.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE
- .github/config.yml
> Add GitHub issue template, pull request template, and welcome config

- .github/move.yml
Allows us to easily move issues (e.g., to avogadrolibs)
https://probot.github.io/apps/move/
Version 1.1
Suite D4700
license and I have the right under that license …
> Add a template for the move-issue bot:

- avogadro/mainwindow.cpp
Version 1.1
Suite D4700
work with …
> Minor Mac nit-pick -- warning for save-on-close should be a sheet.

- avogadro/mainwindow.cpp
Needed by the VTK volume rendering branch.
> Active objects

- avogadro/mainwindow.cpp
Helps to fix https://github.com/OpenChemistry/avogadrolibs/pull/450
Version 1.1
Suite D4700
work with …
> Make sure to send Extensions the setActiveWidget call

- avogadro/mainwindow.cpp
Thanks to @anubh4v for the bug report
Version 1.1
Suite D4700
license and I have the right under that …
> Fixes #125 - labels toolbar windows for context menu

- avogadro/application.cpp
Discussed here: https://discuss.avogadro.cc/t/font-increase-in-high-resolution-screena
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate open …
> Enable Qt::AA_EnableHighDpiScaling - should fix UI text size

- flatpak/org.openchemistry.Avogadro2.yaml
> Make Avogadro work with Molequeue

- avogadro/application.cpp
- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
Fixes #101
Fixes https://github.com/OpenChemistry/avogadrolibs/issues/513
Version 1.1
Suite D4700
license …
> Handle drag-and-drop of files to the window

- flatpak/org.openchemistry.Avogadro2.metainfo.xml
> add developer name

- avogadro/application.cpp
- avogadro/avogadro.cpp
Version 1.1
Suite D4700
work with …
> Make sure to set high-dpi before creating the app object

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Version 1.1
Suite D4700
work with …
> Add release drafter workflow to gather release  notes

- avogadro/avogadro.cpp
- avogadro/mainwindow.cpp
Fixes #99
Version 1.1
Suite D4700
work …
> Save background color across sessions and set bg alpha for export

- avogadro/lastinstall/CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Fix typo in last commit

- scripts/avogadro-remote.py
Version 1.1
Suite D4700
work with …
> Update script for py3 and cross-platform TMPDIR access

- flatpak/org.openchemistry.Avogadro2.metainfo.xml
> Fix bullet points

- cmake/AvogadroCPack.cmake
> Make sure to install data (e.g., fragments, crystals)

- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
Nice, but I'd like to ask for feedback before merging
Version 1.1
Suite D4700 …
> Add a drag-and-drop to install scripts

- .github/workflows/build_cmake.yml
Version 1.1
Suite D4700
work with …
> Try the avogadrolibs builder

- CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Bump version for 1.94 release

- cmake/AvogadroCPack.cmake
Version 1.1
Suite D4700
work with …
> Install obmm binary (for forcefield) and libinchi

- cmake/AvogadroCPack.cmake
Version 1.1
Suite D4700
work with …
> Try enabling the "bundle" for Win installers

- avogadro/mainwindow.cpp
Version 1.1
Suite D4700
work with …
> Set opaque default background color - QColor(r, g, b, a) takes int

- avogadro/CMakeLists.txt
- avogadro/avogadro.cpp
Also grabs Qt and QtBase QM files for bundle on Mac/Win
Version 1.1
Suite D4700 …
> Should now download and install QM translations for Avo

- avogadro/mainwindow.cpp
> Fix avogadrolibs#682 - save projection on close

- avogadro/mainwindow.cpp
Version 1.1
Suite D4700
work with …
> Save enabled / disabled state of scene / rendering plugins on quit

- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
> Layer system

- i18n/hu.po
> Fix hu translation

- avogadro/CMakeLists.txt
- avogadro/avogadro.cpp
> Fix i18n bugs

- avogadro/mainwindow.ui
- i18n/avogadroapp.pot
Version 1.1
Suite D4700
work with …
> Remove old Avo1 actions from mainwindow.ui and update template

- avogadro/mainwindow.cpp
- avogadro/menubuilder.cpp
Also adjust '...' to '…'
Version 1.1
Suite D4700
license and I have the right under that license to …
> Make sure Export -> Molecule and Export -> Graphics are first

- avogadro/mainwindow.cpp
- avogadro/menubuilder.cpp
Reverts OpenChemistry/avogadroapp#219 - breaks multiple actions for some reason...
> Revert "Make sure Export -> Molecule and Export -> Graphics are first"

- avogadro/mainwindow.cpp
- avogadro/menubuilder.cpp
Version 1.1
Suite D4700
work with …
> Restore menu priority - returns Export: Molecule, Graphics

- i18n/avogadroapp.pot
- scripts/extract-messages.sh
> Only update pot template

- avogadro/CMakeLists.txt
- avogadro/mainwindow.cpp
- avogadro/tooltipfilter.cpp
- avogadro/tooltipfilter.h
Not sure why tooltips aren't appearing anywhere, but it's a start
Version 1.1
Suite D4700
license and I …
> Convert Enter events for tool buttons to tooltips

- avogadro/aboutdialog.ui
- avogadro/mainwindow.ui
Version 1.1
Suite D4700
work with …
> Update a few strings, particularly links as https and key shortcuts

- avogadro/avogadro.cpp
Version 1.1
Suite D4700
work with …
> Check downloaded i18n paths for translations too

- .gitmodules
Version 1.1
Suite D4700
work with …
> Fix submodule to use HTTPS

- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
Fixes #248
Version 1.1
Suite D4700
work …
> Add a copy graphics action

- cmake/BuildType.cmake
- cmake/CompilerFlags.cmake
Version 1.1
Suite D4700
work with …
> Add sanitizer build flags to the app

- CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Bump for version 1.96 release

- flatpak/org.openchemistry.Avogadro2.Molequeue.desktop
- flatpak/org.openchemistry.Avogadro2.metainfo.xml
- flatpak/org.openchemistry.Avogadro2.yaml
> update to Flatpak manifest to 1.96.0

- avogadro/CMakeLists.txt
- avogadro/icons/avogadro2.appdata.xml
Thanks to @kevinsmia1939 and @sagitter for their work
Version 1.1
Suite D4700 …
> Add avogadro2.appdata.xml - based on Flatpak and Fedora versions

- avogadro/avogadro.cpp
Fixes #206 #207
Version 1.1
Suite D4700 …
> After successfully loading a translation, do not continue to load

- .github/workflows/codacy.yml
- scripts/filter_sarif.py
Version 1.1
Suite D4700
work with …
> Add Codacy scan to mirror avogadrolibs

- avogadro/CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Make sure to install qt base translations for Mac and Windows

- avogadro/avogadro.cpp
- avogadro/mainwindow.cpp
- avogadro/viewfactory.cpp
Fix avogadrolibs #952
Fix avogadrolibs #955
Version 1.1
Suite D4700
license and I have the right under …
> Fix translation errors with About menu item and 3D View button

- avogadro/avogadro.cpp
- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
Fixes #263 hopefully
Version 1.1
Suite D4700
license and I have the right under that license to submit …
> Add support for localized language dialog

- avogadro/avogadro.cpp
- avogadro/mainwindow.cpp
Version 1.1
Suite D4700
work with …
> Make sure to translate "System Language"

- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
> Tweak strings

- avogadro/mainwindow.cpp
Version 1.1
Suite D4700
work with …
> Add support for installing charge scripts

- CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Request C++17 standard

- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
Version 1.1
Suite D4700
work with …
> Don't use the MainWindow UI file (but don't delete it either)

- avogadro/avogadro.cpp
Fix #285
Version 1.1
Suite D4700
work with …
> Make sure to load a user-selected locale.

- avogadro/mainwindow.cpp
Fix #267 - probably requires an update of the translation files too
Version 1.1
Suite D4700
license and I …
> Fix an untranslated "File"

- CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Update for 1.97.0 release

- flatpak/org.openchemistry.Avogadro2.yaml
> update avogadro to 1.97.0 and enable VTK

- avogadro/icons/avogadro2.desktop
It would be great to figure out a way to automate this
Version 1.1
Suite D4700 …
> Update with Hungarian translation for desktop file

- avogadro/avogadro.cpp
Fix #308
Version 1.1
Suite D4700
work with …
> Add "American English" option to the language list

- .codacy.yaml
Version 1.1
Suite D4700
work with …
> Add codacy config (specifically for cppcheck)

- scripts/avogadro-remote.py
Version 1.1
Suite D4700
work with …
> Minor cleanup of avogadro-remote script, run black

- scripts/avogadro-remote.py
Version 1.1
Suite D4700
work with …
> Added some basic docstrings and cleaned up.

- avogadro/mainwindow.cpp
Version 1.1
Suite D4700
work with …
> Fix a few Edit menu priorities

- cmake/AvogadroCPack.cmake
Version 1.1
Suite D4700
work with …
> Make sure packages include the genXrdPattern binary

- cmake/AvogadroCPack.cmake
Version 1.1
Suite D4700
work with …
> Make sure to check if genxrd exists before installing it

- avogadro/CMakeLists.txt
- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
- avogadro/renderingdialog.cpp
- avogadro/renderingdialog.h
- avogadro/renderingdialog.ui
Complementary to https://github.com/OpenChemistry/avogadrolibs/pull/1123
Signed-off-by: Aritz Erkiaga <aerkiaga3@gmail.com>
Version 1.1
Suite D4700
license and I …
> Add "rendering" dialog to set solid pipeline parameters

- avogadro/CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Ignore deprecated warnings (i.e., Qt 5.15)

- avogadro/renderingdialog.ui
Version 1.1
Suite D4700
work with …
> Switch labels to plain text for translation

- avogadro/mainwindow.cpp
Turns off all other scene plugins (bad)
Version 1.1
Suite D4700
license and I have the right under that …
> Fix bug with setActiveDisplayTypes() called by QTAIM

- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
- avogadro/rpclistener.cpp
- scripts/avogadro-remote.py
Version 1.1
Suite D4700
work with …
> Add support for RPC saveGraphic message with filename

- avogadro/aboutdialog.cpp
- avogadro/aboutdialog.ui
> Add a space for the SSL version number (to help with Win debugging)

- .github/workflows/build_cmake.yml
- .github/workflows/clang-format-check.yml
- .github/workflows/codeql.yml
- .github/workflows/misspell-fixer.yml
> Update build actions from avogadrolibs

- avogadro/lastinstall/CMakeLists.txt
> Switch to version-agnostic image formats

- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
> Put the molecule dock on top of the layer dock by default

- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
- avogadro/rpclistener.cpp
> Initial support for handling extension and tool RPC commands

- cmake/AvogadroCPack.cmake
> Remove the cpack instructions .. don't work

- avogadro/lastinstall/CMakeLists.txt
> Make sure to get the bundle path

- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
- setPerspective
- setRenderTypes
Version 1.1
Suite D4700
work with modifications, whether created in …
> Add some script command enhancements.

- avogadro/mainwindow.cpp
> Add support for installing energy scripts

- CMakeLists.txt
- SECURITY.md
> Update for pending 1.98 release

- CMakeLists.txt
> Bump version number for 1.98.1 release

- i18n/en_AU.po
- i18n/en_CA.po
> [no-ci] Update Australian and Canadian localization from GB

- avogadro/mainwindow.cpp
> Save and load the camera modelView and projection matrix

- cmake/deploy-osx.cmake.in
> Try to fixup bundle with cpack again to fix Mac issues

- avogadro/mainwindow.cpp
> Tweak UI for display settings based on "…" indicators

- avogadro/mainwindow.cpp
Fixes #479
Version 1.1
Suite D4700
by …
> Fix crash when no selection is made when saving files

- avogadro/mainwindow.cpp
- avogadro/mainwindow.h
- avogadro/renderingdialog.cpp
- avogadro/renderingdialog.h
- avogadro/renderingdialog.ui
issue : https://github.com/OpenChemistry/avogadrolibs/issues/347
signed-off by: permindersingh089@gmail.com
complimentary to : https://github.com/OpenChemistry/avogadrolibs/pull/1672 
Version 1.1
Suite D4700
of my knowledge, …
> Added fog as rendering options.

- avogadro/renderingdialog.ui
> Tweak the text and tooltips in the rendering dialog

- avogadro/CMakeLists.txt
> Further fixes for Qt6

- avogadro/mainwindow.cpp
Only seems to be the one instance in `avogadroapp`.
---
Version 1.1
Suite D4700
work with …
> Port QRegExp to QRegularExpression

- avogadro/renderingdialog.ui
> Tweak text in the rendering dialog

- avogadro/mainwindow.cpp
> Make sure to create directories for drag-and-drop scripts

- avogadro/mainwindow.cpp
Version 1.1
Suite D4700
work with …
> Disable code for register Molequeue - can bring back when it's updated

- avogadro/avogadro.cpp
> Update desktop file name in QApplication code

- avogadro/mainwindow.cpp
- avogadro/viewfactory.cpp
- avogadro/viewfactory.h
> Ensure "split" buttons don't create a transparent background

- avogadro/avogadro.cpp
- avogadro/mainwindow.cpp
> Fix windows debug log

- avogadro/mainwindow.cpp
> Add even more debugging

- avogadro/mainwindow.cpp
> Fix install for scripts, esp. energy calculators

- avogadro/avogadro.cpp
> Add version information to the avogadro2.log on Windows

- avogadro/mainwindow.cpp
> Only output debugging bits on Windows (for Win10 launch issues)

- avogadro/mainwindow.cpp
> Add support for QtTesting under Qt6

- CMakeLists.txt
- SECURITY.md
> Bump build to 1.100.0 for release

- README.md
> Update readme to match avogadrolibs

- thirdparty/3DConnexion/inc/SpaceMouse/CCookieCollection.hpp
Hopefully this will fix the problem
Version 1.1
Suite D4700
work with modifications, whether created …
> Windows Qt6 build is failing due to std::chrono issue

- avogadro/mainwindow.cpp
> Ensure the display type list is sorted

- avogadro/mainwindow.cpp
Fixes #571
Version 1.1
Suite D4700
by …
> Fix crash when changing display types

- .github/workflows/add_artifact_urls.yml
- .github/workflows/build_cmake.yml
- .github/workflows/build_flatpak.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_m1.yml
- .github/workflows/build_qt6.yml
- .github/workflows/build_windows.yml
> Synchronize workflows

- .github/workflows/build_linux.yml
> Bundle libssl and libcrypto with AppImage

- .github/workflows/build_linux.yml
> Use system eigen

- avogadro/mainwindow.cpp
> Fix bug with fog not starting with the correct background color

- CMakeLists.txt
- SECURITY.md
> Bump for 1.101 release

- avogadro/CMakeLists.txt
> Make sure JKQtPlotter5 / 6 is included (with avogadrolibs change)

- avogadro/CMakeLists.txt
> build: fix JKQTPlotter path
